export {default as LoginFarmer} from './LoginFarmer';
export {default as SignUpFarmer} from './SignUpFarmer';
export{ default as HomepageFarmer} from './HomepageFarmer';
export {default as BuyMachines} from './BuyMachines';
export {default as ResidueDetails} from './ResidueDetails';
export { default as SellResidue} from './SellResidue';
export { default as ChangePassword} from './ChangePassword';
export {default as Cart} from './Cart';
export {default as Connections} from './Connections';
export {default as MachineFarmer} from './MachineFarmer';
export {default as Profile} from './Profile';
export {default as Rent} from './Rent';
export {default as Settings} from './Settings';
export{default as Footer } from './Footer';
export { default as SideNavBar} from './SideNavBar';
// export {default as Forms} from './Forms';
// export{default as Navbar} from './Navbar';